DROP TABLE IF EXISTS ADDRESS;

CREATE TABLE ADDRESS (
    FIRST TEXT NOT NULL,
    LAST TEXT NOT NULL,
    ADDRESS TEXT NOT NULL,
    CITY TEXT NOT NULL,
    STATE TEXT NOT NULL,
    COUNTRY TEXT NOT NULL
);
